<?php

namespace AppBundle\Repository;

/**
 * CalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalleRepository extends \Doctrine\ORM\EntityRepository
{

}
