<?php

namespace AppBundle\Repository;

/**
 * InterseccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterseccionRepository extends \Doctrine\ORM\EntityRepository
{
	
 
}
